version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - ./:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
